import { createMiddleware } from 'hono/factory';
import type { Env } from '../types';

/**
 * Auto-generated secret when API_SECRET is not configured.
 * Persists for the lifetime of the Worker instance (until next cold start).
 */
let _autoGeneratedSecret: string | null = null;

export const authMiddleware = createMiddleware<{ Bindings: Env }>(async (c, next) => {
  let secret = c.env.API_SECRET;

  // If API_SECRET is not configured, auto-generate a cryptographically random secret
  // and log it prominently. This prevents silent open access.
  if (!secret) {
    if (!_autoGeneratedSecret) {
      // Generate a random 48-character hex string (192 bits)
      const randomBytes = new Uint8Array(24);
      crypto.getRandomValues(randomBytes);
      _autoGeneratedSecret = Array.from(randomBytes)
        .map(b => b.toString(16).padStart(2, '0'))
        .join('');

      const warning = [
        '╔══════════════════════════════════════════════════════════════╗',
        '║  [SECURITY] API_SECRET environment variable is NOT set!      ║',
        '║  An auto-generated temporary secret has been created.        ║',
        '║                                                            ║',
        `║  Auto-generated secret: ${_autoGeneratedSecret}`,
        '║                                                            ║',
        '║  WARNING: This secret will CHANGE on each Worker cold start.║',
        '║  Set API_SECRET in your environment variables for a fixed   ║',
        '║  secret in production deployments.                          ║',
        '╚══════════════════════════════════════════════════════════════╝',
      ].join('\n');
      console.error(warning);
    }
    secret = _autoGeneratedSecret;
  }

  const authHeader = c.req.header('Authorization');
  if (!authHeader?.startsWith('Bearer ')) {
    return c.json({ error: { code: 'UNAUTHORIZED', message: 'Missing or invalid authorization header' } }, 401);
  }
  if (authHeader.substring(7) !== secret) {
    return c.json({ error: { code: 'FORBIDDEN', message: 'Invalid API secret' } }, 403);
  }
  await next();
});
