#!/usr/env node
/**
 * gen-version.js
 *
 * 从 CHANGELOG.md 提取最新版本号，并通过 git 获取当前 commit（短 SHA），
 * 生成供 worker 与 backend 使用的 version.ts 文件。
 *
 * 唯一真实来源: CHANGELOG.md 中第一个 `## [x.y.z]` 标题
 * 生成产物:     worker/src/version.ts
 *               backend/src/version.ts
 *
 * 环境变量:
 *   GIT_COMMIT    若设置（非空）则优先作为 git commit，否则回退到 `git rev-parse`
 *   BACKEND_SRC   自定义 backend 版本文件输出目录（Docker 构建时 backend 源码位于 /app/src）
 *
 * 用法:
 *   node scripts/gen-version.js            # 生成 worker + backend 的 version.ts
 *   node scripts/gen-version.js worker     # 仅生成 worker
 *   node scripts/gen-version.js backend    # 仅生成 backend
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const root = path.resolve(__dirname, '..');

function extractVersion() {
  const changelog = path.join(root, 'CHANGELOG.md');
  if (!fs.existsSync(changelog)) {
    console.warn('[gen-version] WARNING: CHANGELOG.md not found, falling back to "0.0.0"');
    return '0.0.0';
  }
  const content = fs.readFileSync(changelog, 'utf-8');
  const match = content.match(/^##\s+\[(\d+\.\d+\.\d+)\]/m);
  if (!match) {
    console.warn('[gen-version] WARNING: no version header found in CHANGELOG.md, falling back to "0.0.0"');
    return '0.0.0';
  }
  return match[1];
}

function getGitCommit() {
  const envCommit = process.env.GIT_COMMIT;
  if (envCommit && envCommit.trim()) {
    return envCommit.trim();
  }
  try {
    return execSync('git rev-parse --short HEAD', { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return '';
  }
}

function generate(targetName, outPath) {
  const version = extractVersion();
  const gitCommit = getGitCommit();
  const banner = '// AUTO-GENERATED by scripts/gen-version.js — do not edit manually';
  const content = `${banner}\nexport const VERSION = '${version}';\nexport const GIT_COMMIT = '${gitCommit}';\n`;

  const dir = path.dirname(outPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  let existing = '';
  try { existing = fs.readFileSync(outPath, 'utf-8'); } catch {}
  if (existing !== content) {
    fs.writeFileSync(outPath, content, 'utf-8');
    console.log(`[gen-version] wrote ${targetName}: v${version}${gitCommit ? ' (' + gitCommit + ')' : ''}`);
  } else {
    console.log(`[gen-version] ${targetName} up to date: v${version}${gitCommit ? ' (' + gitCommit + ')' : ''}`);
  }
}

const targets = {
  worker: path.join(root, 'worker', 'src', 'version.ts'),
  backend: process.env.BACKEND_SRC
    ? path.join(process.env.BACKEND_SRC, 'version.ts')
    : path.join(root, 'backend', 'src', 'version.ts'),
};

const arg = process.argv[2];
if (arg && targets[arg]) {
  generate(arg, targets[arg]);
} else {
  for (const [name, outPath] of Object.entries(targets)) {
    generate(name, outPath);
  }
}
